"""
RESILIA Optimization Models — Sprint 3
======================================
Pydantic data models for OR-Tools resource redistribution,
surplus evaluation, operational intervention plans, and
human-in-the-loop approval workflows.
"""
from __future__ import annotations

import uuid
from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field


class SurplusCandidate(BaseModel):
    """Candidate facility evaluated as a potential redistribution source."""
    phc_id: str
    phc_name: str
    district: str
    state: str
    lat: float
    lng: float
    current_stock: float
    daily_consumption: float
    current_days: float
    safety_stock_days: float = 7.0
    safety_stock_units: float
    surplus_days: float
    available_surplus_units: float
    distance_km: float
    eta_hours: float
    is_cross_district: bool
    risk_severity: str = "LOW"
    expiry_days: int = 180


class OptimizationRequest(BaseModel):
    """Parameters for running the OR-Tools reallocation engine."""
    target_phc_id: str
    medicine_code: str
    target_stock_days: float = Field(default=14.0, description="Desired runway at target PHC")
    safety_stock_days: float = Field(default=7.0, description="Minimum runway preserved at source PHCs")
    vehicle_capacity: float = Field(default=3000.0, description="Max units transportable per vehicle")
    max_distance_km: float = Field(default=400.0, description="Maximum redistribution radius")
    allow_cross_district: bool = True
    min_surplus_days: float = Field(default=3.0, description="Minimum surplus days required to consider source")


class AllocationRoute(BaseModel):
    """Single transfer route determined by the OR-Tools optimization engine."""
    route_id: str = Field(default_factory=lambda: f"ROUTE-{uuid.uuid4().hex[:8].upper()}")
    source_phc_id: str
    source_name: str
    source_district: str
    destination_phc_id: str
    destination_name: str
    destination_district: str
    is_cross_district: bool
    medicine_code: str
    medicine_name: str
    quantity: float
    distance_km: float
    eta_hours: float
    vehicle_id: str
    transport_cost_inr: float
    remaining_source_stock_days: float


class OptimizationResult(BaseModel):
    """Direct output of the OR-Tools solver formulation."""
    status: str                          # "OPTIMAL" | "FEASIBLE" | "INFEASIBLE" | "NO_SURPLUS"
    solver_name: str = "Google OR-Tools SCIP (Mixed-Integer Linear Programming)"
    objective_value: float
    runtime_ms: float
    target_phc_id: str
    medicine_code: str
    medicine_name: str
    deficit_units: float
    total_allocated_units: float
    unmet_deficit_units: float
    allocated_routes: list[AllocationRoute]
    candidates_evaluated: int
    surplus_candidates: list[SurplusCandidate] = []
    constraints_satisfied: list[str] = []


class InterventionImpact(BaseModel):
    """Forecasted clinical impact of executing the intervention."""
    pre_stock_days: float
    post_stock_days: float
    stock_out_avoided: bool = True
    days_gained: float
    risk_reduction_pct: float


class InterventionConfidence(BaseModel):
    """Confidence assessment computed by the Response Agent."""
    rating: str                          # "HIGH" | "MEDIUM" | "LOW"
    score_pct: float                     # e.g. 94.2
    factor_breakdown: dict[str, str] = {}


class OperationalInterventionPlan(BaseModel):
    """
    Complete human-in-the-loop intervention plan generated by
    the Response Agent wrapping OR-Tools optimization.
    """
    plan_id: str = Field(default_factory=lambda: f"INTV-{uuid.uuid4().hex[:8].upper()}")
    created_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())
    status: str = "AWAITING_APPROVAL"     # "AWAITING_APPROVAL" | "APPROVED" | "MODIFIED" | "REJECTED" | "EXECUTED"

    # Clinical Context
    target_phc_id: str
    target_phc_name: str
    target_district: str
    medicine_code: str
    medicine_name: str

    # Agent Explanations & Operational Sections
    title: str
    problem_summary: str
    recommended_action: str
    expected_impact: str
    impact_metrics: InterventionImpact

    # Logistics & Transport
    transport_summary: str
    primary_source_phc_id: str
    primary_source_phc_name: str
    primary_source_district: str
    is_cross_district: bool
    total_units: float
    eta_hours: float
    assigned_vehicle_id: str

    # Confidence & Solver Details
    confidence: InterventionConfidence
    routes: list[AllocationRoute]
    optimization_result: OptimizationResult

    # Human-in-the-loop lifecycle
    approved_by: Optional[str] = None
    approved_at: Optional[str] = None
    rejection_reason: Optional[str] = None
    modification_notes: Optional[str] = None

    # Step Functions Execution trace
    workflow_execution: Optional[dict] = None


class PlanApprovalRequest(BaseModel):
    """Human approval submission."""
    approved_by: str
    note: Optional[str] = "Approved: Surplus validated, logistics corridor cleared."


class PlanModifyRequest(BaseModel):
    """Human modification before re-approving."""
    modified_by: str = "District Logistics Officer"
    override_quantity: Optional[float] = None
    selected_source_phc_id: Optional[str] = None
    notes: Optional[str] = None


class PlanRejectRequest(BaseModel):
    """Human rejection submission."""
    rejected_by: str = "District Health Officer"
    reason: str
